---
title: "keras-multiplication"
author: "Sean Fitzgerald"
date: "3/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install libraries
```{r}
# install.packages("devtools")
# devtools::install_github("rstudio/keras")
library(keras)
use_python("/Users/sean/.pyenv/shims/python")
# install_keras(method = "conda", conda = "/Users/sean/.pyenv/shims/conda")
```

## Generate data
```{r}
numSequences <- 500L
sequenceLength <- 4L
numSteps <- sequenceLength - 1L
numInputs <- 1L

generateSampleData <- function(numSequences, sequenceLength, numInputs) {
  sequences <- array(
    0L,
    c(numSequences, sequenceLength, numInputs)
  )
  for (i in 1:numSequences) {
    base <- i / numSequences
    sequences[i,,] <- matrix(c(base, base*2, base*4, base*8), nrow=sequenceLength, ncol=numInputs)
  }
  return(sequences)
}

sequences <- generateSampleData(numSequences, sequenceLength, numInputs)
sequences[1,1,1]*2 == sequences[1,2,1]
```

## Create train and test sets
```{r}
trainSetSize <- round(.8*numSequences)
trainIndexIndices <- sample(1:numSequences, trainSetSize)

#add drop = F to not lose dimensions when indexing
xTrain <- sequences[trainIndexIndices,1:numSteps,,drop = F]
yTrain <- sequences[trainIndexIndices,sequenceLength,]

xTest <- sequences[-trainIndexIndices,1:numSteps,, drop = F]
yTest <- sequences[-trainIndexIndices,sequenceLength,]
```

```{r}
# this will clear the current graph for creating new models/layers. It errors out but still clears the graph
k_clear_session()
```

## Create model
```{r}
model <- keras_model_sequential()

model %>%
  layer_simple_rnn(1, input_shape = c(numSteps,numInputs)) %>%
  layer_dense(1)

model %>% compile(
  optimizer = optimizer_sgd(lr=0.003),
  loss = "mse"
)

summary(model)
```
## Test model
```{r}
history <- model %>% fit(xTrain, yTrain, epochs = 100, verbose=F)
plot(history)
```
## Predict on train and test sets
```{r}
predictions <- model %>% predict(xTrain)
plot(
  1:length(predictions),
  predictions,
  type="l",
  col="red",
  ylim=c(min(c(predictions, yTrain)), max(c(predictions, yTrain))),
  main="Prediction on Training Set"
  )
lines(1:length(yTrain), yTrain, type="l")
legend(5, y = 8, c("Prediction", "Actual"), c("red", "black"))

predictions <- model %>% predict(xTest)
plot(
  1:length(predictions),
  predictions,
  type="l",
  col="red",
  ylim=c(min(c(predictions, yTest)), max(c(predictions, yTest))),
  main="Prediction on Test Set"
  )
lines(1:length(yTest), yTest, type="l")
legend(5, y = 8, c("Prediction", "Actual"), c("red", "black"))
```
